export interface Material {
  id: string;
  name: string;
  code: string;
  sub_category :any;
  barcode:string;
  base_uom:any;
  sale_uom:any;
  conversion_formula:string;
  hs_code:string;
  remarks :string;
  image :string;
  unit_price :string;
  mat_lock_status:boolean;
  tpt_no:string;
  dimensions:string;
  volume_unit:string;
  volume:String;
  weight :string;
  gross_weight :string;
  net_weight:string;
  weight_unit:string;
  mat_width:string;
  mat_height:string;
  mat_length :string;
  reorder_level :string;
  min_qty :string;
  max_qty :string;
  old_material_code :string;
  ean_category :string;
  ean_ups_category:string;
  status: boolean;
  material_developer :string;
  composition :string;
  construction :string;
  thickness :string;
  mat_release_status:string;
  first_season:any;
  dev_type :string;
  creation_date?: string;
  update_date?: string;
}
